-- Migration 28: Add ai_discussion_prompt column.
-- A short closing sentence (1-2 phrases) generated by Gemini alongside the
-- summary, inviting the reader to comment on the article. Stored separately
-- from ai_summary so it can be rendered with its own style and iterated on
-- independently.

ALTER TABLE articles
  ADD COLUMN ai_discussion_prompt text;
