-- A1: SEO-optimized title for news articles.
-- Feeds <title>, og:title and the visible <h1> (with `seo_title || title` fallback
-- everywhere). Generated by Gemini at scrape time for new articles; existing
-- articles are left untouched (NULL) and backfilled on demand from the admin.
-- Nullable, no default, no backfill: old rows keep rendering their `title`.

ALTER TABLE articles ADD COLUMN IF NOT EXISTS seo_title text;
